name: 'Runtime checks'
description: 'Run dynamic analysis tools'

runs:
  using: "composite"
  steps:
    - name: Sanitizers
      shell: bash
      # run one sanitizer for each env to avoid building extra binaries on one env
      if: matrix.runs_asan == true && runner.os != 'Windows'
      # detect_leaks is not supported on macOS
      # env:
      #   ASAN_OPTIONS: detect_leaks=1
      run: |
        # run server in background
        ./${{ env.ZIP_NAME }}/"${EXECUTABLE_NAME}" &
        # run client in foreground
        cat "${INPUT_FILENAME}" | tr -d '\r' | ./${{ env.ZIP_NAME }}/"${EXECUTABLE_NAME}-client"
        # wait for server shutdown
        sleep 6

    - name: Sanitizers (Windows MSVC)
      shell: bash
      # run one sanitizer for each OS to avoid building extra binaries
      if: matrix.cxx == 'cl' && matrix.runs_asan == true
      continue-on-error: true
      run: |
        # run server in background
        ./${{ env.ZIP_NAME }}/"${EXECUTABLE_NAME}".exe &
        # run client in foreground
        cat "${INPUT_FILENAME}" | ./${{ env.ZIP_NAME }}/"${EXECUTABLE_NAME}-client".exe
        # wait for server shutdown
        sleep 6

    - name: Valgrind
      shell: bash
      if: runner.os == 'Linux' && matrix.runs_valgrind == true
      run: |
        bash ./scripts/run_valgrind.sh "${{ env.ZIP_NAME }}"
