name: 'Create release'
description: 'Create releases for tags'

runs:
  using: "composite"
  steps:
    - name: Set Tag Name
      shell: bash
      if: startsWith(github.ref, 'refs/tags/')
      # trim prefix from ref to get tag name
      # replace `/` since we use the tag name as part of a file name
      run: echo "TAG_NAME=$(echo ${GITHUB_REF#'refs/tags/'} | sed "s|/|_|g")" >> ${GITHUB_ENV}

    - name: Add tag to folder name
      shell: bash
      if: startsWith(github.ref, 'refs/tags/')
      run: |
        mv ${{ env.ZIP_NAME }} ${{ env.ZIP_NAME }}_${{ env.TAG_NAME }}

    - name: Archive Release
      # renovate: datasource=github-tags depName=thedoctor0/zip-release versioning=loose
      uses: thedoctor0/zip-release@0.7.6
      if: startsWith(github.ref, 'refs/tags/')
      with:
        type: 'zip'
        path: ${{ env.ZIP_NAME }}_${{ env.TAG_NAME }}
        filename: ${{ env.ZIP_NAME }}_${{ env.TAG_NAME }}.zip

    - name: Generate artifact attestation
      # renovate: datasource=github-tags depName=actions/attest-build-provenance versioning=loose
      uses: actions/attest-build-provenance@v3.0.0
      if: ${{ startsWith(github.ref, 'refs/tags/') && ! env.PRIVATE_REPO }}
      with:
        subject-path: ${{ env.ZIP_NAME }}_${{ env.TAG_NAME }}.zip

    - name: Release
      # renovate: datasource=github-tags depName=softprops/action-gh-release versioning=loose
      uses: softprops/action-gh-release@v2.3.2
      if: startsWith(github.ref, 'refs/tags/')
      with:
        files: |
          ${{ env.ZIP_NAME }}_${{ env.TAG_NAME }}.zip
