name: 'Configure PostgreSQL'
description: 'Common logic for PostgreSQL configuration'

runs:
  using: "composite"
  steps:
    - name: Start Linux PostgreSQL service
      shell: bash
      if: runner.os == 'Linux'
      run: |        
        sudo systemctl start postgresql.service
        sudo -u postgres bash ./scripts/configure_postgres.sh

    - name: Start MacOS PostgreSQL service
      shell: bash
      if: runner.os == 'macOS'
      run: |
        brew install postgresql
        brew services start postgresql@14
        bash ./scripts/configure_postgres.sh

    - name: Start Windows PostgreSQL service
      shell: bash
      if: runner.os == 'windows'
      run: |
        serviceName="postgresql-x64-14"
        sc config $serviceName start= demand
        net start $serviceName
        export PGPASSWORD="root"
        export PATH="$PATH:/c/Program Files/PostgreSQL/14/bin:/c/Program Files/PostgreSQL/14/lib"
        bash ./scripts/configure_postgres.sh