name: 'Configure PostgreSQL'
description: 'Common logic for PostgreSQL configuration'

runs:
  using: "composite"
  steps:
    - name: Start Linux PostgreSQL service
      shell: bash
      if: runner.os == 'Linux'
      run: |
          sudo service postgresql start

    - name: Start MacOS PostgreSQL service
      shell: bash
      if: runner.os == 'macOS'
      run: |
        brew install postgresql
        brew services start postgresql
        sudo pg_ctl -D /usr/local/var/postgres start

    - name: Start Windows PostgreSQL service
      shell: bash
      if: runner.os == 'windows'
      run: |
        net start postgresql-x64-14

    - name: Initialize database
      shell: bash
      run: |
        PGPASSWORD=$POSTGRES_PASSWORD psql -h $POSTGRES_HOST -U $POSTGRES_USER -c "CREATE DATABASE oop;"
      env:
        POSTGRES_HOST: localhost
        POSTGRES_USER: postgres
        POSTGRES_PASSWORD: root