name: 'Configure CMake'
description: 'Common logic for CMake configuration'
inputs:
  cmake_generator:
    description: 'CMake generator'
    required: false
  warnings_as_errors:
    description: 'Treat warnings as errors'
    required: false
    default: 'ON'
  custom_flags:
    description: 'Custom CMake configuration flags'
    required: false

# outputs:
#   random-number:
#     description: "Random number"
#     value: ${{ steps.random-number-generator.outputs.random-number }}
runs:
  using: "composite"
  steps:
    - run: |
          CMAKE_GENERATOR=${{ inputs.cmake_generator }} cmake -S ${GITHUB_WORKSPACE} -B "${BUILD_DIR}" \
            -DCMAKE_BUILD_TYPE=${BUILD_TYPE} \
            -DCMAKE_INSTALL_PREFIX=${GITHUB_WORKSPACE}/artifacts \
            -DGITHUB_ACTIONS=${GITHUB_ACTIONS} \
            -DWARNINGS_AS_ERRORS=${{ inputs.warnings_as_errors }} \
            ${{ inputs.custom_flags }}
      shell: bash
    # - id: random-number-generator
    #   run: echo "random-number=$(echo $RANDOM)" >> $GITHUB_OUTPUT
    #   shell: bash
    # - run: echo "${{ github.action_path }}" >> $GITHUB_PATH
    #   shell: bash
    # - run: goodbye.sh
    #   shell: bash
