#!/usr/bin/bash

psql -h 127.0.0.1 -U postgres -c "CREATE USER $DATABASE_USER WITH CREATEDB PASSWORD '$DATABASE_PASSWORD';"
psql -h 127.0.0.1 -U postgres -c "CREATE DATABASE $DATABASE_NAME WITH OWNER $DATABASE_USER;"
psql -h 127.0.0.1 -U postgres -d $DATABASE_NAME -c "CREATE EXTENSION IF NOT EXISTS pgcrypto;"