name: 'Run cppcheck'
description: 'Install and run cppcheck'

runs:
  using: "composite"
  steps:
    - name: Cache cppcheck
      # renovate: datasource=github-tags depName=actions/cache versioning=loose
      uses: actions/cache/restore@v5.0.3
      id: cache-cppcheck
      with:
        path: cppcheck
        key: cppcheck-${{ env.CPPCHECK_VER }}

    - name: Install packages
      uses: ./.github/actions/install-packages

    - name: Build cppcheck
      shell: bash
      if: steps.cache-cppcheck.outputs.cache-hit != 'true'
      run: |
        bash ./scripts/build_cppcheck.sh -v ${CPPCHECK_VER}

    - name: Save cppcheck cache
      # renovate: datasource=github-tags depName=actions/cache versioning=loose
      uses: actions/cache/save@v5.0.3
      if: steps.cache-cppcheck.outputs.cache-hit != 'true'
      with:
        path: cppcheck
        key: cppcheck-${{ env.CPPCHECK_VER }}

    - name: Install cppcheck
      shell: bash
      # this step is fast, no need for caching
      run: |
        cd cppcheck
        sudo cmake --install build

    - name: Configure CMake
      uses: ./.github/actions/configure-cmake
      with:
        custom_flags: '-GNinja'
        cache_key: 'cache-cppcheck'

    - name: Cppcheck
      shell: bash
      run: |
        bash ./scripts/run_cppcheck.sh
