name: 'Run cppcheck'
description: 'Install and run cppcheck'

runs:
  using: "composite"
  steps:
    # The flag CMAKE_EXPORT_COMPILE_COMMANDS generates compile_commands.json
    # which is used by cppcheck and clang-tidy
    - name: Configure CMake
      uses: ./.github/actions/configure-cmake
      with:
        custom_flags: '-DCMAKE_EXPORT_COMPILE_COMMANDS=ON -G Ninja'

    - name: Cppcheck
      shell: bash
      run: |
        bash ./scripts/run_cppcheck.sh
