name: 'Process artifacts'
description: 'Process artifact files'

runs:
  using: "composite"
  steps:
    - name: Patch macOS launcher
      shell: bash
      if: runner.os == 'macOS'
      run: |
        sed -i '' -e "s/oop/${EXECUTABLE_NAME}/" "${{ env.ZIP_NAME }}/launcher.command"
        chmod +x "${{ env.ZIP_NAME }}/launcher.command"

    - name: Patch Windows launcher
      shell: bash
      if: runner.os == 'Windows'
      run: |
        sed -i -e "s/oop/${EXECUTABLE_NAME}/" "${{ env.ZIP_NAME }}/launcher.bat"
        chmod +x "${{ env.ZIP_NAME }}/launcher.bat"

    - name: Copy missing dylibs
      shell: bash
      if: runner.os == 'macOS' && matrix.cxx == 'clang++'
      run: |
        mkdir -p ${{ env.ZIP_NAME }}/lib
        if [[ "${BUILD_TYPE}" =~ "Deb" ]]; then
          install_name_tool -change @rpath/libclang_rt.asan_osx_dynamic.dylib @executable_path/lib/libclang_rt.asan_osx_dynamic.dylib ${{ env.ZIP_NAME }}/${{ env.EXECUTABLE_NAME }}.app/Contents/MacOS/${{ env.EXECUTABLE_NAME }}
        fi
        mv ${{ env.ZIP_NAME }}/lib ${{ env.ZIP_NAME }}/${{ env.EXECUTABLE_NAME }}.app/Contents/MacOS

    - name: Copy missing dylibs (g++)
      shell: bash
      if: runner.os == 'macOS' && startsWith(matrix.cxx, 'g++')
      run: |
        mkdir -p ${{ env.ZIP_NAME }}/lib
        cp /opt/homebrew/lib/gcc/13/libstdc++.6.dylib /opt/homebrew/lib/gcc/13/libgcc_s.1.1.dylib ${{ env.ZIP_NAME }}/lib
        install_name_tool -change /opt/homebrew/lib/gcc/13/libstdc++.6.dylib @executable_path/lib/libstdc++.6.dylib ${{ env.ZIP_NAME }}/${{ env.EXECUTABLE_NAME }}.app/Contents/MacOS/${{ env.EXECUTABLE_NAME }}
        install_name_tool -change /opt/homebrew/lib/gcc/13/libgcc_s.1.1.dylib @executable_path/lib/libgcc_s.1.1.dylib ${{ env.ZIP_NAME }}/${{ env.EXECUTABLE_NAME }}.app/Contents/MacOS/${{ env.EXECUTABLE_NAME }}
        mv ${{ env.ZIP_NAME }}/lib ${{ env.ZIP_NAME }}/${{ env.EXECUTABLE_NAME }}.app/Contents/MacOS

    - name: Copy missing dlls
      shell: bash
      if: runner.os == 'Windows' && matrix.cxx == 'cl'
      run: |
        if [[ "${BUILD_TYPE}" =~ "Deb" ]]; then
          # runtime debug DLLs
          cp "$(which ucrtbased.dll)" \
             "$(which VCRUNTIME140_1D.dll)" \
             "$(which MSVCP140D.dll)" \
             "$(which VCRUNTIME140D.dll)" \
             ${GITHUB_WORKSPACE}/${{ env.ZIP_NAME }}

          # sanitizers DLLs
          vcver=$(cat "C:/Program Files/Microsoft Visual Studio/2022/Enterprise/VC/Auxiliary/Build/Microsoft.VCToolsVersion.default.txt")
          vcbindir="C:/Program Files/Microsoft Visual Studio/2022/Enterprise/VC/Tools/MSVC/${vcver}/bin/Hostx64/x64/"
          cp "${vcbindir}/clang_rt.asan_dynamic-x86_64.dll" \
             "${vcbindir}/clang_rt.asan_dbg_dynamic-x86_64.dll" \
             ${GITHUB_WORKSPACE}/${{ env.ZIP_NAME }}
        fi

        # runtime release DLLs
        if [[ "${BUILD_TYPE}" =~ "Rel" ]]; then
          cp "$(which ucrtbase.dll)" \
             "$(which VCRUNTIME140_1.dll)" \
             "$(which MSVCP140.dll)" \
             "$(which VCRUNTIME140.dll)" \
             ${GITHUB_WORKSPACE}/${{ env.ZIP_NAME }}
        fi

    - name: Copy stdlib (MinGW)
      shell: bash
      if: runner.os == 'Windows' && matrix.cxx == 'g++'
      # static linking might not work with MinGW, might be easier this way
      run: |
        cp gcc/mingw64/bin/libstdc++-6.dll \
          gcc/mingw64/bin/libgcc_s_seh-1.dll \
          gcc/mingw64/bin/libwinpthread-1.dll \
          ${GITHUB_WORKSPACE}/${{ env.ZIP_NAME }}

      # copy only for debug purposes
    - name: Copy AppImage file
      shell: bash
      if: runner.os == 'Linux'
      run: |
        cp ${{ env.BUILD_DIR }}/${{ env.EXECUTABLE_NAME }}.AppImage ${GITHUB_WORKSPACE}/${{ env.ZIP_NAME }}
