###############################################################################
# Framework agnostic registration of test executables with CTest.
#
# NOTE: this file and cmake/RegisterTestsAddTests.cmake hold no test framework specific code.
#
#   register_tests(<target>)
#       one CTest test for the whole executable. This is all a plain assert()
#       based test needs: nothing has to be able to list or select a case.
#
#   register_tests(<target> LIST_ARGS <arg> [SELECT_ARG <template>] ...)
#       one CTest test per test case. <arg> makes the executable print its
#       test cases, one per line (boost::ut: "--list-test-names-only",
#       googletest: "--gtest_list_tests"); <template> is the argument that
#       runs a single case, with <name> replaced by the case name
#       (boost::ut: "<name>", googletest: "--gtest_filter=<name>").
#
# Options (all optional):
#   LIST_ARGS <arg>          how to list the test cases (see above)
#   LIST_NOISE <regex>       removed from every line of the listing, a line left
#                            empty is not a test case (^ and $ are not per line)
#   SELECT_ARG <template>... how to run one test case, <name> is the placeholder,
#                            several arguments are passed as separate arguments
#   NAME_ESCAPE <characters> characters that must be replaced with "?" (any
#                            single character) in a case name before it is handed
#                            back to the executable as a selection argument.
#                            Needed by frameworks whose selection argument is a
#                            pattern rather than an exact name (see below).
#   TIMEOUT <seconds>        per test timeout, default 60, so a hung test cannot
#                            hang CI forever
#   LIST_TIMEOUT <seconds>   timeout for the listing run, default 60; the first
#                            run right after linking is slow on Windows/ASan
#   WORKING_DIRECTORY <dir>  default CMAKE_SOURCE_DIR, tests open assets/ and
#                            the default (the build directory) breaks that
#   TEST_LIST <variable>     set in the calling scope to the list of test names
#   PROPERTIES <name value>  extra CTest test properties
###############################################################################

# CMAKE_CURRENT_LIST_DIR inside a function body is the file of the *caller*, so
# remember where this module lives while it is being included
set(REGISTER_TESTS_MODULE_DIR "${CMAKE_CURRENT_LIST_DIR}")

function(register_tests TARGET)
    cmake_parse_arguments(PARSE_ARGV 1 ARG "" "LIST_ARGS;LIST_NOISE;NAME_ESCAPE;TIMEOUT;LIST_TIMEOUT;WORKING_DIRECTORY;TEST_LIST" "SELECT_ARG;PROPERTIES")

    if(NOT TARGET ${TARGET})
        message(FATAL_ERROR "register_tests: ${TARGET} is not a target")
    endif()

    if(ARG_UNPARSED_ARGUMENTS)
        message(FATAL_ERROR "register_tests: unknown arguments: ${ARG_UNPARSED_ARGUMENTS}")
    endif()

    if(NOT DEFINED ARG_WORKING_DIRECTORY)
        set(ARG_WORKING_DIRECTORY "${CMAKE_SOURCE_DIR}")
    endif()

    if(NOT DEFINED ARG_TIMEOUT)
        set(ARG_TIMEOUT 60)
    endif()

    if(NOT DEFINED ARG_LIST_TIMEOUT)
        set(ARG_LIST_TIMEOUT 60)
    endif()

    ###############################################################################

    if(NOT ARG_LIST_ARGS)
        # nothing can enumerate the cases (plain assert() tests): one test
        add_test(NAME ${TARGET} COMMAND ${TARGET})

        set_tests_properties(${TARGET} PROPERTIES
            WORKING_DIRECTORY "${ARG_WORKING_DIRECTORY}"
            TIMEOUT "${ARG_TIMEOUT}"
            ${ARG_PROPERTIES}
        )

        if(DEFINED ARG_TEST_LIST)
            set(${ARG_TEST_LIST} ${TARGET} PARENT_SCOPE)
        endif()

        return()
    endif()

    ###############################################################################

    # The list of cases is only known by running the executable, so the tests
    # cannot be registered at configure time. Discovery runs inside ctest
    # (before the first test), never as part of the build: the build of a test
    # must not run tests, an ASan crash while listing looks like a build
    # failure and CI would not tell the two apart.
    # Same TEST_INCLUDE_FILES mechanism as gtest_discover_tests(DISCOVERY_MODE PRE_TEST)

    get_property(GENERATOR_IS_MULTI_CONFIG GLOBAL PROPERTY GENERATOR_IS_MULTI_CONFIG)

    set(file_base "${CMAKE_CURRENT_BINARY_DIR}/ctest_${TARGET}")
    set(include_file "${file_base}_include.cmake")

    if(GENERATOR_IS_MULTI_CONFIG)
        set(tests_file "${file_base}_tests-$<CONFIG>.cmake")
    else()
        set(tests_file "${file_base}_tests.cmake")
    endif()

    # regenerated by cmake, it only includes the file written at test time
    string(CONCAT include_content
        "if(EXISTS \"$<TARGET_FILE:${TARGET}>\")"                                     "\n"
        "  if(NOT EXISTS \"${tests_file}\" OR"                                        "\n"
        "     NOT \"${tests_file}\" IS_NEWER_THAN \"$<TARGET_FILE:${TARGET}>\" OR\n"
        "     NOT \"${tests_file}\" IS_NEWER_THAN \"\${CMAKE_CURRENT_LIST_FILE}\")\n"
        "    include(\"${REGISTER_TESTS_MODULE_DIR}/RegisterTestsAddTests.cmake\")\n"
        "    register_tests_discover("                                                "\n"
        "      TEST_EXECUTABLE"    " [==[" "$<TARGET_FILE:${TARGET}>"     "]==]"      "\n"
        "      TEST_WORKING_DIR"   " [==[" "${ARG_WORKING_DIRECTORY}"     "]==]"      "\n"
        "      LIST_ARGS"          " [==[" "${ARG_LIST_ARGS}"             "]==]"      "\n"
        "      LIST_NOISE"         " [==[" "${ARG_LIST_NOISE}"            "]==]"      "\n"
        "      SELECT_ARG"         " [==[" "${ARG_SELECT_ARG}"            "]==]"      "\n"
        "      NAME_ESCAPE"        " [==[" "${ARG_NAME_ESCAPE}"           "]==]"      "\n"
        "      LIST_TIMEOUT"       " [==[" "${ARG_LIST_TIMEOUT}"          "]==]"      "\n"
        "      TIMEOUT"            " [==[" "${ARG_TIMEOUT}"               "]==]"      "\n"
        "      TEST_LIST"          " [==[" "${ARG_TEST_LIST}"             "]==]"      "\n"
        "      TEST_PROPERTIES"    " [==[" "${ARG_PROPERTIES}"            "]==]"      "\n"
        "      CTEST_FILE"         " [==[" "${tests_file}"                "]==]"      "\n"
        "    )"                                                                       "\n"
        "  endif()"                                                                   "\n"
        "  include(\"${tests_file}\")"                                                "\n"
        "else()"                                                                      "\n"
        "  add_test(${TARGET}_NOT_BUILT ${TARGET}_NOT_BUILT)"                         "\n"
        "endif()"                                                                     "\n"
    )

    if(GENERATOR_IS_MULTI_CONFIG)
        foreach(config IN LISTS CMAKE_CONFIGURATION_TYPES)
            file(GENERATE OUTPUT "${file_base}_include-${config}.cmake" CONTENT "${include_content}" CONDITION $<CONFIG:${config}>)
        endforeach()
        file(WRITE "${include_file}" "include(\"${file_base}_include-\${CTEST_CONFIGURATION_TYPE}.cmake\")")
    else()
        file(GENERATE OUTPUT "${file_base}_include.cmake" CONTENT "${include_content}")
        file(WRITE "${include_file}" "include(\"${file_base}_include.cmake\")")
    endif()

    set_property(DIRECTORY APPEND PROPERTY TEST_INCLUDE_FILES "${include_file}")

    if(DEFINED ARG_TEST_LIST)
        message(WARNING "register_tests: TEST_LIST is only set by ctest, after the cases were discovered")
    endif()
endfunction()
