name: Renovate CI
on:
  workflow_dispatch: {}

jobs:
  renovate:
    runs-on: ubuntu-22.04
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        
      - name: Run Renovate
        uses: renovatebot/github-action@v43.0.6
        env:
          LOG_LEVEL: debug
          RENOVATE_REPOSITORIES: ${{ github.repository }}
          RENOVATE_ONBOARDING: "false"
          RENOVATE_REQUIRE_CONFIG: "optional"
        with:
          token: ${{ secrets.RENOVATE_TOKEN }}
          configurationFile: .github/renovate_ci.json
